CREATE TABLE Creators (
  id INT NOT NULL AUTO_INCREMENT,
  creator VARCHAR(50) NOT NULL UNIQUE,
  marks VARCHAR(50) DEFAULT '',
  info VARCHAR(100),
  fav INT(8) NOT NULL DEFAULT 0,
  refcount INT NOT NULL DEFAULT 0,
  titlecount INT NOT NULL DEFAULT 0,
  PRIMARY KEY(id)
) DEFAULT CHARSET=utf8;
