CREATE TABLE `pictures` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  `creator` varchar(50) NOT NULL,
  `path` varchar(500) NOT NULL,
  `mark` varchar(10) DEFAULT NULL,
  `info` varchar(100) DEFAULT NULL,
  `fav` char(1) DEFAULT '0',
  `count` int(8) DEFAULT 0,
  `bindata` int(11) DEFAULT 0,
  `date` date DEFAULT NULL,
  `sn` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `PATH` (`PATH`),
  KEY `pictures_title` (`TITLE`),
  KEY `pictures_path` (`PATH`),
  KEY `pictures_cretator` (`CREATOR`),
  KEY `pictures_info` (`INFO`),
  KEY `pictures_mark` (`MARK`),
  KEY `pictures_date` (`date`),
  KEY `pictures_sn` (`sn`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
